# Generated by Django 3.1.2 on 2020-10-22 22:42

from django.db import migrations, models
import speechrecognition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LemmaCounter',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('word_lemma', models.CharField(default='<ukn>', max_length=100)),
                ('date_said', models.DateTimeField(verbose_name='Date said on')),
                ('week_number_said', models.PositiveSmallIntegerField(default=43, validators=[speechrecognition.models.validate_week_number])),
            ],
        ),
        migrations.CreateModel(
            name='SentimentLemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma_written_form', models.CharField(max_length=100)),
                ('sense_confidence_level', models.CharField(max_length=100)),
                ('sentiment_polarity', models.CharField(choices=[('POS', 'positive'), ('NEG', 'negative')], default='NEG', max_length=3)),
                ('part_of_speech', models.CharField(choices=[('ADJE', 'adjective'), ('NOUN', 'noun'), ('VERB', 'verb'), ('OTHE', 'other')], default='OTHE', max_length=4)),
            ],
        ),
    ]
