# Generated by Django 3.1.2 on 2020-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechrecognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmacounter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
