# Generated by Django 3.1.2 on 2020-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechrecognition', '0002_auto_20201024_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemmacounter',
            name='week_number_said',
            field=models.PositiveSmallIntegerField(default=43),
        ),
    ]
