# Generated by Django 3.1.2 on 2020-10-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechrecognition', '0003_auto_20201024_0834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LemmaCounter',
            new_name='LemmaSaid',
        ),
    ]
