# Generated by Django 3.1.2 on 2020-10-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speechrecognition', '0005_auto_20201024_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidlemma',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='speechrecognition.sentimentlemma'),
        ),
    ]
