# Generated by Django 3.1.2 on 2020-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentlemma',
            name='part_of_speech',
            field=models.CharField(choices=[('ADJE', 'adjective'), ('NOUN', 'noun'), ('VERB', 'verb')], default='VERB', max_length=4),
        ),
    ]
