# Generated by Django 3.1.2 on 2020-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_recognition', '0003_auto_20201019_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lemmacounter',
            name='sentiment_lemma',
        ),
        migrations.AddField(
            model_name='lemmacounter',
            name='word_lemma',
            field=models.CharField(default='<ukn>', max_length=100),
        ),
    ]
